# Generated by Django 4.2.6 on 2023-10-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportingDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="supporting_docs/")),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("eligibility", models.TextField()),
                ("link", models.URLField()),
                ("project_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "supporting_docs",
                    models.ManyToManyField(to="GreenThumb.supportingdoc"),
                ),
            ],
        ),
    ]
