# Generated by Django 4.2.6 on 2023-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "employee_count",
                    models.CharField(
                        choices=[
                            ("<20", "<20"),
                            ("20-49", "20-49"),
                            ("50-249", "50-249"),
                            ("250+", "250+"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "annual_electricity_budget",
                    models.CharField(
                        choices=[
                            ("<$50k", "<$50k"),
                            ("$50k-$100k", "$50k-$100k"),
                            ("$100k-$250k", "$100k-$250k"),
                            ("$250k+", "$250k+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "annual_natural_gas_budget",
                    models.CharField(
                        choices=[
                            ("<$50k", "<$50k"),
                            ("$50k-$100k", "$50k-$100k"),
                            ("$100k-$250k", "$100k-$250k"),
                            ("$250k+", "$250k+"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Program",
        ),
        migrations.DeleteModel(
            name="SupportingDoc",
        ),
    ]
