# Generated by Django 4.2.6 on 2023-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0002_company_delete_program_delete_supportingdoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_sector",
            field=models.CharField(
                choices=[
                    ("Advanced Manufacturing", "Advanced Manufacturing"),
                    ("Agriculture", "Agriculture"),
                    ("Biotech/Laboratories", "Biotech/Laboratories"),
                    ("Colleges/Universities", "Colleges/Universities"),
                    ("Commercial Real Estate", "Commercial Real Estate"),
                    ("Dairy", "Dairy"),
                    ("Data Centers", "Data Centers"),
                    ("Electrification", "Electrification"),
                    ("Food Processing", "Food Processing"),
                    ("Government", "Government"),
                    ("Greenhouses", "Greenhouses"),
                    ("Grocery", "Grocery"),
                    ("Healthcare", "Healthcare"),
                    ("Hospitality", "Hospitality"),
                    ("K-12 Schools", "K-12 Schools"),
                    ("Livestock", "Livestock"),
                    ("New Construction", "New Construction"),
                    ("Parking Garages/Lots", "Parking Garages/Lots"),
                    ("Public Assembly", "Public Assembly"),
                    ("Restaurant", "Restaurant"),
                    (
                        "Residential (Multi-Unit Residential)",
                        "Residential (Multi-Unit Residential)",
                    ),
                    ("Retail", "Retail"),
                    ("Senior Living", "Senior Living"),
                    ("Warehouses & Cold Storage", "Warehouses & Cold Storage"),
                    (
                        "Water Distribution/Wastewater Treatment",
                        "Water Distribution/Wastewater Treatment",
                    ),
                    ("Service Retail", "Service Retail"),
                    ("Small/Medium Sized Businesses", "Small/Medium Sized Businesses"),
                ],
                default="Advanced Manufacturing",
                max_length=50,
            ),
        ),
    ]
