# Generated by Django 4.2.6 on 2023-10-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0005_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="annual_electricity_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="companies_by_electricity_budget",
                to="GreenThumb.electricitybudget",
            ),
        ),
    ]
