# Generated by Django 4.2.6 on 2023-10-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0006_company_annual_electricity_budget"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarketSegment",
            new_name="Companysector",
        ),
        migrations.AddField(
            model_name="company",
            name="annual_natural_gas_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies_by_gas_budget",
                to="GreenThumb.naturalgasbudget",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies_by_sector",
                to="GreenThumb.companysector",
            ),
        ),
    ]
