# Generated by Django 4.2.6 on 2023-10-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0008_alter_company_annual_natural_gas_budget_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Program",
            new_name="Programs",
        ),
    ]
