# Generated by Django 4.2.6 on 2023-10-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0010_program_delete_programs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Program",
            new_name="Programs",
        ),
    ]
