# Generated by Django 4.2.6 on 2023-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0011_rename_program_programs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programs",
            name="eligible_company_sector",
        ),
        migrations.AddField(
            model_name="programs",
            name="eligible_company_sector",
            field=models.ManyToManyField(
                related_name="programs_to_sector", to="GreenThumb.companysector"
            ),
        ),
    ]
