# Generated by Django 4.2.6 on 2023-10-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0012_remove_programs_eligible_company_sector_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Programs",
            new_name="Program",
        ),
    ]
