# Generated by Django 4.2.6 on 2023-10-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GreenThumb", "0013_rename_programs_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="eligible_annual_electricity_budget",
        ),
        migrations.RemoveField(
            model_name="program",
            name="eligible_annual_natural_gas_budget",
        ),
        migrations.RemoveField(
            model_name="program",
            name="eligible_employee_count",
        ),
        migrations.AddField(
            model_name="program",
            name="eligible_annual_electricity_budget",
            field=models.ManyToManyField(
                related_name="programs_by_electricity_budget",
                to="GreenThumb.electricitybudget",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="eligible_annual_natural_gas_budget",
            field=models.ManyToManyField(
                related_name="programs_by_gas_budget", to="GreenThumb.naturalgasbudget"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="eligible_employee_count",
            field=models.ManyToManyField(
                related_name="programs_by_employee_count", to="GreenThumb.employeecount"
            ),
        ),
    ]
