# Generated by Django 4.2.6 on 2023-10-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "GreenThumb",
            "0014_remove_program_eligible_annual_electricity_budget_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_info",
            field=models.EmailField(max_length=100),
        ),
    ]
